### ISSUE TITLE
Failed creating new xdo instance

### ISSUE THREAD

**Issue by DQ318** [nathanharper/Chiquitita#1]
Hi @nathanharper, everything ok?

I was trying to run your app and after installing everything needed, when typing the command:

./run_http.sh super_mario.smc

I come across the following errors:
```
Error: Can't open display: (null)
Failed creating new xdo instance
ZSNES_ID is
Opening 'http://35.247.254.102:80' with default browser.
./run_http.sh: line 17: xdg-open: command not found
Server PID: 22212
root@instance-1:/home/treizecontato/snes# events.js:183
      throw er; // Unhandled 'error' event
      ^


Error: listen EADDRINUSE :::80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/home/treizecontato/snes/server/server.js:49:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
Error: Can't open display: (null)
> Failed creating new xdo instance
> ZSNES_ID is
> Opening 'http://35.247.254.102:80' with default browser.
> ./run_http.sh: line 17: xdg-open: command not found
> Server PID: 22212
> root@instance-1:/home/treizecontato/snes# events.js:183
>       throw er; // Unhandled 'error' event
```

However, when opening the browser, a snes control appears and says that the status is online, but the zsnes emulator does not open together.
Could you help me solve it?
Your app is active in: http://35.247.254.102/

Thank you!

**Comment by nathanharper** [comment]
Hi, DQ318! Thanks for checking out the project.

I haven't tried to run this in a while, but from your error I'd assume that the problem is that you're trying to run this on OSX, and I apparently wrote these bash scripts targeting linux.

You should be able to get around this by patching the run_http.sh script to use `open` rather than `xdg-open`. When I have free time, I'll patch it to check the environment.

Let me know if you run into any other platform issues!

**Comment by DQ318** [comment]
@nathanharper hi man!

Actually, I'm running the application on a UBUNTU 18.04 - 64bit, hosted on Google Cloud Plattaform.
I had to allow access to 32 bits packages in the ubuntu, because the ZSNES package is only available for 32 bits, does it have any association?

**Comment by nathanharper** [comment]
@DQ318 that's odd, I thought that was a default install on ubuntu. do you see anything when you run `which xdg-open`? You might need to (re)install `xdg-utils`. I don't _think_ the 32 bit package thing is a problem, but that's interesting to note.

**Comment by DQ318** [comment]
@nathanharper 

When I type:
`which xdg-open` returns: `/usr/bin/xdg-open`

And running the command to start the app, the errors have changed a bit after reinstalling the XDG-UTILS package:

```
Use ZSNES -? for command line definitions.

Starting Mouse detection.
ManyMouse: 1 mice detected.
Error opening file!

Error: Can't open display: (null)
Failed creating new xdo instance
ZSNES_ID is
Opening 'http://35.247.254.102:80' with default browser.
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: x-www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: firefox: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: google-chrome: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://35.247.254.102:80'
Server PID: 26429
root@instance-1:/home/treizecontato/snes# events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/home/treizecontato/snes/server/server.js:49:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
^
```

**Comment by nathanharper** [comment]
If you check out that error, `xdg-open` is looking for a command line tool to launch a browser, but it can't find anything. I can't recall exactly how i set this up, but I imagine you'd get whatever browser you want's CLI executable by installing it via `apt-get`, so you may want to apt-get install chromium or something and see if that does the trick.

**Comment by DQ318** [comment]
@nathanharper 

Really ... Lack of attention from me, sorry man =D
But even installing chromium and firefox, apparently the error persists.

```
File opened successfully !
./run_http.sh: line 22:  2828 Segmentation fault      (core dumped) zsnes "$1"
Error: Can't open display: (null)
Failed creating new xdo instance
ZSNES_ID is
[2836:2836:0619/211203.756605:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Server PID: 2835
root@instance-1:/home/treizecontato/snes# events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/home/treizecontato/snes/server/server.js:49:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12
```

**Comment by nathanharper** [comment]
Hmmm, it looks like the `zsnes` CLI command itself segfaulted. I'm not sure why it would do that, but it could be a problem with the ROM. What are you trying to open? I would suggest trying to run a couple ROMs from the command line (`zsnes path/to/rom`) to see if it's a faulty install or just your ROM.

**Comment by nathanharper** [comment]
I just did a little google research and it seems like this might be a result of the 32/64 bit confusion :/

I'm on my work macbook at the moment, but I'll do some troubleshooting when I get some time.

https://ubuntuforums.org/archive/index.php/t-1866752.html
